FROM dunglas/frankenphp

ARG USER=appuser
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd -g ${GROUP_ID} ${USER} && \
    useradd -l -u ${USER_ID} -g ${USER} -s /bin/bash ${USER} && \
    usermod -aG sudo ${USER}

RUN install-php-extensions \
    pcntl \
    pdo_mysql \
    intl \
    gd
    # Add other PHP extensions here...

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY uploads.ini /usr/local/etc/php/conf.d/uploads.ini

RUN mkdir -p /app && chown -R ${USER}:${USER} /app

USER ${USER}

WORKDIR /app

COPY . /app
